export const junkItems = [
  {
    id: "mattress",
    name: "Mattress",
    price: 75,
    icon: "🛏️",
    popular: true,
  },
  {
    id: "box_spring",
    name: "Box Spring",
    price: 50,
    icon: "📦",
    popular: true,
  },
  {
    id: "dresser",
    name: "Dresser",
    price: 65,
    icon: "🗄️",
    popular: true,
  },
  {
    id: "recliner",
    name: "Recliner",
    price: 80,
    icon: "🪑",
    popular: true,
  },
  {
    id: "bag_of_junk",
    name: "Bag of Junk",
    price: 25,
    icon: "🛍️",
    popular: true,
  },
  {
    id: "couch",
    name: "Couch / Loveseat",
    price: 100,
    icon: "🛋️",
    popular: true,
  },
  {
    id: "desk",
    name: "Desk",
    price: 70,
    icon: "🖥️",
    popular: true,
  },
  {
    id: "treadmill",
    name: "Treadmill",
    price: 120,
    icon: "/icons/treadmill.png", // Updated path
    popular: true,
  },
  {
    id: "refrigerator",
    name: "Refrigerator",
    price: 150,
    icon: "❄️",
  },
  {
    id: "washing_machine",
    name: "Washing Machine",
    price: 100,
    icon: "🧺",
  },
  {
    id: "dryer",
    name: "Dryer",
    price: 100,
    icon: "👕",
  },
  {
    id: "dishwasher",
    name: "Dishwasher",
    price: 90,
    icon: "🍽️",
  },
  {
    id: "tv",
    name: "Television",
    price: 60,
    icon: "📺",
  },
  {
    id: "bookshelf",
    name: "Bookshelf",
    price: 55,
    icon: "📚",
  },
  {
    id: "table",
    name: "Table",
    price: 70,
    icon: "🪑",
  },
  {
    id: "chair",
    name: "Chair",
    price: 30,
    icon: "🪑",
  },
  {
    id: "bicycle",
    name: "Bicycle",
    price: 45,
    icon: "🚲",
  },
  {
    id: "grill",
    name: "Grill",
    price: 65,
    icon: "🍖",
  },
  {
    id: "lawnmower",
    name: "Lawnmower",
    price: 75,
    icon: "🌱",
  },
  {
    id: "tire",
    name: "Tire",
    price: 20,
    icon: "🛞",
  },
  {
    id: "exercise_machine",
    name: "Exercise machine",
    price: 90,
    icon: "/icons/Exercise-machine.png",
  },
  {
    id: "hot_tub",
    name: "Hot Tub",
    price: 250,
    icon: "/icons/hot-tub.png",
  },
  {
    id: "large_item",
    name: "Large Item",
    price: 100,
    icon: "/icons/large-item.png",
  },
  {
    id: "small_item",
    name: "Small Item",
    price: 30,
    icon: "/icons/small-item.png",
  },
  {
    id: "medium_item",
    name: "Medium Item",
    price: 60,
    icon: "/icons/medium-item.png",
  },
  {
    id: "debris",
    name: "Debris",
    price: 40,
    icon: "/icons/debris.png",
  },
  {
    id: "electronic_unlisted",
    name: "Electronic (Unlisted)",
    price: 50,
    icon: "/icons/electronic.png",
  },
  {
    id: "sleeper_sofa",
    name: "Sleeper Sofa",
    price: 120,
    icon: "/icons/sleeper-sofa.png",
  },
  {
    id: "sectional_2_piece",
    name: "Sectional (2 Piece)",
    price: 150,
    icon: "/icons/sectional-2-piece.png",
  },
  {
    id: "sectional_3_piece",
    name: "Sectional (3 Piece)",
    price: 200,
    icon: "/icons/sectional-3-piece.png",
  },
  {
    id: "range",
    name: "Range",
    price: 110,
    icon: "/icons/range.png",
  },
  {
    id: "ac_unit",
    name: "AC Unit",
    price: 85,
    icon: "/icons/AC-unit.png",
  },
  {
    id: "trampoline",
    name: "Trampoline",
    price: 130,
    icon: "/icons/trampoline.png",
  },
]
